### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yesCurtis** [kghost/premade-filter#1]
How did you go about finding the information you needed to update this?

Like, how did you know what to look for and find these id's? 
Just incase I have to update it on my own in the future.

**Comment by kghost** [comment]
https://mods.curse.com/addons/wow/premade-filter#c308

**Comment by yesCurtis** [comment]
No, I understand and have done that, it's updated. I was asking how you went about finding out how to update it, where is the code? the ID's how did you know that was where to add it?
